version: "3"
services:
  fastapi:
    container_name: remotest_fastapi
    build: Backend/
    restart: always
    ports:
      - 9004:9004
    volumes:
      - ./Backend/src:/src
    working_dir: /src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    environment:
      - TZ=Asia/Tokyo

  php:
    container_name: remotest_php
    image: php:8.2-apache
    ports:
      - 8500:80
    volumes:
      - ./Frontend/src:/var/www/html
      - ./Frontend/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Tokyo

  cloudflared:
    image: cloudflare/cloudflared
    container_name: remotest_cloudflared
    command: tunnel run
    env_file:
      - compose.env